defaults: &defaults
  adapter: postgresql
  database: <%= ENV["PROD_DB_NAME"] || 'owls_nest' %>
  encoding: unicode
  host: <%= ENV["PROD_HOSTNAME"] || 'localhost' %>
  password: <%= ENV["PROD_PASSWD"] %>
  pool: 5
  port: <%= ENV["PROD_PORT"] || 5432 %>
  username: <%= ENV["PROD_USERNAME"] || 'sched' %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default

qa:
  <<: *default
